services:
  postgres_test:
    image: postgres:16
    container_name: py-users-api-pg-test
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d testdb"]
      interval: 2s
      timeout: 2s
      retries: 30
    volumes:
      - ./tests/sql/init.sql:/docker-entrypoint-initdb.d/001_init.sql:ro
